// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: Blog/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for AppSettings (scope: System.App)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppSettings data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.DetailsPage`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.App.
  /// </remarks>
  public partial class AppSettings: AutoGenerated.ZAutoGenAppSettings
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'AppSettings' in scope 'System.App'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAppSettings: Custom.Data.CustomItem
  {
    /// <summary>
    /// DetailsPage as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("DetailsPage")
    /// </summary>
    public string DetailsPage => _item.Url("DetailsPage");

    /// <summary>
    /// Get the file object for DetailsPage - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile DetailsPageFile => _item.File("DetailsPage");

    /// <summary>
    /// Get the folder object for DetailsPage.
    /// </summary>

    [JsonIgnore]
    public IFolder DetailsPageFolder => _item.Folder("DetailsPage");

    /// <summary>
    /// RssButtonInCategories as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("RssButtonInCategories", scrubHtml: true) etc.
    /// </summary>
    public string RssButtonInCategories => _item.String("RssButtonInCategories", fallback: "");

    /// <summary>
    /// ShowShareBtn as bool. <br/>
    /// To get nullable use .Get("ShowShareBtn") as bool?;
    /// </summary>
    public bool ShowShareBtn => _item.Bool("ShowShareBtn");
  }
}